TWEAK_NAME = mopttnoads

mopttnoads_FILES = mopttnoads.x
mopttnoads_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
mopttnoads_FRAMEWORKS = UIKit

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
